# cli_flow.cmake - the terminal-only acceptance path: sim open -> buttons to Settings -> sim state reports the
# path -> sim shot writes a colour PNG -> sim close. Runs on a copy of the project so sim/storage stays clean.
# cmake -DSIM=<sim exe> -DSRC=<repo>/sim -DWORK=<build>/cli_flow -P tests/cli_flow.cmake
file(REMOVE_RECURSE ${WORK})
file(COPY ${SRC}/ DESTINATION ${WORK})
function(sim)
  execute_process(COMMAND ${SIM} ${ARGN} --project ${WORK} RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err)
  if(NOT rc EQUAL 0)
    execute_process(COMMAND ${SIM} close --project ${WORK})
    message(FATAL_ERROR "sim ${ARGN} failed (${rc}): ${out}${err}")
  endif()
  set(OUT "${out}" PARENT_SCOPE)
endfunction()
sim(open)
sim(wait 5400)
sim(press OK)
sim(press CANCEL)
foreach(i RANGE 1 5)
  sim(press RIGHT)
endforeach()
sim(press OK)
sim(state --json)
string(JSON path GET "${OUT}" menu_path)
string(JSON screen GET "${OUT}" screen)
sim(shot ${WORK}/settings.png --scale 2)
sim(close)
if(NOT path STREQUAL "Home/Menu/Settings" OR NOT screen STREQUAL "T0")
  message(FATAL_ERROR "expected Home/Menu/Settings (T0), got ${path} (${screen})")
endif()
file(READ ${WORK}/settings.png head LIMIT 8 HEX)
if(NOT head STREQUAL "89504e470d0a1a0a")
  message(FATAL_ERROR "sim shot didn't write a PNG")
endif()
message(STATUS "terminal flow ok: ${path} (${screen}), PNG written")
