#!/usr/bin/env python3
"""Builds the Import Asset test files in sim/fixtures/ from the built-in asset headers, in the formats
Flipper UI Studio exports (see THEME_FORMAT_SPEC in the studio). Re-run after changing the generator.

  night-theme.zip  theme pack "night": built-in fonts, inverted boot splash, a wrench Settings icon,
                   and a 16x16 Games icon the firmware must reject (menu icons are 12x12)
  moon.b1i         a 32x32 picture for sd:/media
"""
import os
import re
import struct
import zipfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GEN = os.path.join(ROOT, "firmware", "assets", "generated")
OUT = os.path.join(ROOT, "sim", "fixtures")


def header_bytes(name, array):
    text = open(os.path.join(GEN, name)).read()
    body = re.search(array + r"\[\d+\] PROGMEM = \{(.*?)\};", text, re.S).group(1)
    return bytes(int(v, 16) for v in re.findall(r"0x[0-9a-fA-F]{2}", body))


def charset(name, ident):
    text = open(os.path.join(GEN, name)).read()
    raw = re.search(ident + r'_CHARSET\[\] = "(.*)";', text).group(1)
    return raw.encode().decode("unicode_escape").encode("latin-1")


def pack(rows):
    w = len(rows[0])
    out = bytearray((w * len(rows) + 7) // 8)
    for y, row in enumerate(rows):
        for x, c in enumerate(row):
            if c == "#":
                i = y * w + x
                out[i >> 3] |= 1 << (i & 7)
    return bytes(out)


def b1i(w, h, frames, delay=0):
    return b"B1I\x01" + struct.pack("<HHHH", w, h, len(frames), delay) + b"".join(frames)


def b1f(w, h, chars, glyphs):
    return b"B1F\x01" + bytes([w, h]) + struct.pack("<H", len(chars)) + chars + glyphs


def main():
    os.makedirs(OUT, exist_ok=True)
    large = b1f(8, 8, charset("font_large.h", "LARGE"), header_bytes("font_large.h", "LARGE_GLYPHS"))
    small = b1f(6, 8, charset("font_small.h", "SMALL"), header_bytes("font_small.h", "SMALL_GLYPHS"))
    splash = bytes(b ^ 0xFF for b in header_bytes("pic_boot_splash.h", "PIC_BOOT_SPLASH"))
    wrench = pack([
        "............", "........###.", ".......#..#.", "......#.##..", ".....#.#....", "....#.#.....",
        "...#.#......", "..#.#.......", ".#.#........", "#.#.........", ".#..........", "............"])
    big_games = pack(["#" * 16] + ["#" + "." * 14 + "#"] * 14 + ["#" * 16])
    ini = ("; theme.ini - generated by Flipper UI Studio\n[theme]\nname=Night\n"
           "font_large=fonts/large.b1f\nfont_small=fonts/small.b1f\nsplash=splash.b1i\n\n"
           "[icons]\nsettings=icons/settings.b1i\ngames=icons/games.b1i\n")
    base = "system/theme/night/"
    with zipfile.ZipFile(os.path.join(OUT, "night-theme.zip"), "w", zipfile.ZIP_DEFLATED) as z:
        z.writestr(base + "theme.ini", ini)
        z.writestr(base + "fonts/large.b1f", large)
        z.writestr(base + "fonts/small.b1f", small)
        z.writestr(base + "splash.b1i", b1i(128, 160, [splash]))
        z.writestr(base + "icons/settings.b1i", b1i(12, 12, [wrench]))
        z.writestr(base + "icons/games.b1i", b1i(16, 16, [big_games]))
    moon = pack(["".join("#" if (x - 15.5) ** 2 + (y - 15.5) ** 2 < 180 and (x - 21) ** 2 + (y - 11) ** 2 > 120
                         else "." for x in range(32)) for y in range(32)])
    open(os.path.join(OUT, "moon.b1i"), "wb").write(b1i(32, 32, [moon]))
    print("wrote", sorted(os.listdir(OUT)))


if __name__ == "__main__":
    main()
